### PR TITLE
Improve Makefile

### PR DESCRIPTION
**Pull request by paper42**
- removed MANSECTION
- added DESTDIR, PREFIX for simpler packaging in distributions
- replaced mkdir, cp and chmod with install command

I would also remove most of the ifs, @ and if it fails, the user will see the command which failed, not a message specific to this project, but I will leave the decision up to you.

### CODE REVIEW

**Comment by n-ivkovic** [comment]
Apologies for not including DESTDIR and PREFIX, I was not aware importance of these until now.

The script and Makefile are intended to be portable as possible across *nix systems by conforming to POSIX/SUS as much as possible. Due to this, I intend to continue using `mkdir` + `cp` + `chmod` as opposed to `install` as it is not defined in POSIX/SUS, see [here](https://en.wikipedia.org/wiki/List_of_Unix_commands) and [here](https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html). Even on systems where `install` is present, commonly used options such as -D are not available on all implementations, see #2.

If you could remove the usage of `install` from this branch, then I'd be happy to approve this merge into a new feature branch, where it would soon be merged into master. Further portability changes and a possible solution to #7 would be committed and your other recommended changes would be considered before the merge into master would occur.

**Comment by astralchan** [comment]
It appears that the most most important things are the `DESTDIR` and `PREFIX` variables for distributions. If these are implemented, then as for the void package [here](https://github.com/void-linux/void-packages/pull/27113), everything in `do_install()` can be replaced by `build_style=gnu-makefile` as far as I understand. Other changes such as the `install` don't seem to be needed as you mentioned.

**Comment by paper42** [comment]
> The script and Makefile are intended to be portable as possible across *nix systems by conforming to POSIX/SUS as much as possible. Due to this, I intend to continue using `mkdir` + `cp` + `chmod` as opposed to `install` as it is not defined in POSIX/SUS, see [here](https://en.wikipedia.org/wiki/List_of_Unix_commands) and [here](https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html). Even on systems where `install` is present, commonly used options such as -D are not available on all implementations, see #2.

You are right, install command is not in POSIX and -D is a non-standard extension. I will revert my changes, but there are other important portability problems. For example `ifeq` is not available on BSD make. That's one more reason to remove all ifs.

**Comment by n-ivkovic** [comment]
> ...there are other important portability problems. For example `ifeq` is not available on BSD make. That's one more reason to remove all ifs.

You make a good argument for removing the ifs. I planned to address additional portability issues before merging these changes into master, I'll add this to the list.

**Pull request merged**
